apiVersion: v1
kind: Service
metadata:
  name: tpfoyer-service
spec:
  selector:
    app: tpfoyer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer
